# baseURL = "https://examplesite.com/"
languageCode = "en-us"
title = "Bexar Hugo Template"
theme = "bexar-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]
  
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/fontawesome/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery-2.0.0.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.bundle.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/modernizer/modernizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/filterizr/jquery.filterizr.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  


# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  weight = 3
  name = "Free Resources"
  hasChildren = true
  identifier = "FreeResources"
  
  [[menu.main]]
  weight = 4
  name = "Free Assessments"
  hasChildren = true
  identifier = "FreeAssessments"
  
  [[menu.main]]
  weight = 5
  name = "Do It Yourself"
  hasChildren = true
  identifier = "DoItYourself"
  
  [[menu.main]]
  weight = 5
  name = "One-On-One Help"
  hasChildren = true
  identifier = "One-On-One-Help"
  
  [[menu.main]]
  weight = 7
  name = "Chatroom"
  hasChildren = true
  identifier = "Chatroom"
  
  [[menu.main]]
  weight = 6
  name = "About"
  hasChildren = true
  identifier = "About"
  
	
	

  # footer menu
  [[menu.footer]]
  name = "Terms of Service"
  URL = "terms"
  weight = 1
  
  [[menu.footer]]
  name = "Privacy Policy"
  URL = "privacy-policy"
  weight = 2
  
  
  
  

[params]
logo = "images/logo.png"
logoAlt = "images/logo-alt.png"
home = "Home"
# Meta data
description = "Bexar hugo template meta description."
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"
# mailchimp subsciption
mailchimpFormAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e" # replace this url with yours
mailchimpFormName = "b_f95ece2732a6e9925f2e70a61_b1e227529e" # replace this code with yours

  # Preloader
  [params.preloader]
  enable = true

  # search
  [params.search]
  enable = false

  # top header
  [params.topHeader]
  enable = false
  email = "info@bexar.com"
  phone = "1234565525"
    # social icon
    [[params.topHeader.icon]]
    icon = "fa-facebook"
    URL = "https://facebook.com/themefisher"
    [[params.topHeader.icon]]
    icon = "fa-twitter"
    URL = "https://twitter.com/themefisher"
    [[params.topHeader.icon]]
    icon = "fa-github"
    URL = "https://github.com/themefisher"
    [[params.topHeader.icon]]
    icon = "fa-instagram"
    URL = "https://instagram.com/themefisher"

  # Navigation get start button
  [params.navBtn]
  enable = false
  btnText = "get started"
  URL = "service"

  # call to action
  [params.cta]
  enable = true
  title = "How To Overcome ANY Objection Your Wife Has Given You About Your Cuckold/Hotwife Fantasy!"
  bgImage = "images/backgrounds/cta-lg.webp"
  bgImageAlt = "images/backgrounds/cta-lg.jpg"
  btnText = "get an quote"
  URL = "/contact"

  # page sidebar quick contact form
  [params.quickContact]
  enable = true

  # Footer
  [params.footer]
  content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit. <br> Deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem."

    # follow us on social site
    [params.footer.followUs]
    title = "Follow Us On"  

      [[params.footer.followUs.socialIcon]]
      icon = "fa-facebook"
      URL = "https://facebook.com/themefisher"

      [[params.footer.followUs.socialIcon]]
      icon = "fa-twitter"
      URL = "https://twitter.com/themefisher"

      [[params.footer.followUs.socialIcon]]
      icon = "fa-instagram"
      URL = "https://instagram.com/themefisher"

      [[params.footer.followUs.socialIcon]]
      icon = "fa-pinterest"
      URL = "https://pinterest.com/themefisher"

    # Service
    [params.footer.service]
    title = "Services"

      [[params.footer.service.serviceList]]
      name = "Company History"
      URL = "/about"

      [[params.footer.service.serviceList]]
      name = "About Us"
      URL = "/about"

      [[params.footer.service.serviceList]]
      name = "Contact Us"
      URL = "/contact"

      [[params.footer.service.serviceList]]
      name = "Services"
      URL = "/service"

      [[params.footer.service.serviceList]]
      name = "Privacy Policy"
      URL = "/privacy"

    # Contact
    [params.footer.contact]
    title = "Contact Info"

      [[params.footer.contact.contactList]]
      listItem = "9567 Turner Trace Apt. 466 North Willie, BC C3G8A4"

      [[params.footer.contact.contactList]]
      listItem = "+21 123 456 5523"

      [[params.footer.contact.contactList]]
      listItem = "info@bexar.com"

  # newsletter
  [params.newsletter]
  enable = true
  title = "Subscribe Newsletter"

  # copyright
  [params.copyright]
  copyright = "A hugo theme by [themefisher.com](https://themefisher.com) "